theme: jekyll-theme-cayman
title : Airplane Crashes and Fatalities
Description : โปรเควิชา PSIT ของกลุ่ม CivicES นักศึกษาชั้นปีที่ 1 คณะเทคโนโลยีสารสนเทศ สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง
